[package]
name = "rite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34.0"
winit = "0.29.10"
ab_glyph = "0.2.23"
image = "0.24.8"
